import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

let config = {};
const apiUrl = "/api";
let auth;
let currentUser;
let profile;
let feed = [];
let page = location.hash.slice(1) || "home";

const app = document.querySelector("#app");
const initials = (name = "SC") => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const escapeHtml = (value = "") => String(value).replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[char]));
const timeAgo = (date) => { const minutes = Math.max(1, Math.floor((Date.now() - new Date(date)) / 60000)); return minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.floor(minutes / 60)}h` : `${Math.floor(minutes / 1440)}d`; };

function setTheme() { document.documentElement.dataset.theme = localStorage.getItem("skillcircle-theme") || "light"; }
function toggleTheme() { const next = document.documentElement.dataset.theme === "dark" ? "light" : "dark"; localStorage.setItem("skillcircle-theme", next); setTheme(); render(); }
function firebaseReady() { return config.apiKey && config.projectId; }
async function request(path, options = {}) { const token = await currentUser?.getIdToken(); if (!token) throw new Error("Please sign in to continue."); const headers = new Headers(options.headers); headers.set("Authorization", `Bearer ${token}`); if (!(options.body instanceof FormData)) headers.set("Content-Type", "application/json"); const response = await fetch(`${apiUrl}${path}`, { ...options, headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Something went wrong."); return body; }
function shell(content) { return `<header class="topbar"><a class="brand" href="#home"><b>S</b> skillcircle</a><nav><a href="#home">Home</a><a href="#discover">Discover</a><a href="#notifications">Notifications</a><a href="#profile">Profile</a></nav><button class="icon-button" id="theme" title="Toggle theme">${document.documentElement.dataset.theme === "dark" ? "☼" : "◐"}</button><button class="text-button" id="logout">Sign out</button></header>${content}<nav class="bottom-nav"><a href="#home">Home</a><a href="#discover">Discover</a><a class="plus" href="#create">+</a><a href="#notifications">Alerts</a><a href="#profile">Profile</a></nav>`; }
function avatar(person) { return `<div class="avatar">${person?.avatarUrl ? `<img src="${escapeHtml(person.avatarUrl)}" alt="">` : initials(person?.name)}</div>`; }
function bindShell() { document.querySelector("#theme")?.addEventListener("click", toggleTheme); document.querySelector("#logout")?.addEventListener("click", () => signOut(auth)); }

function loginView(message = "") { app.innerHTML = `<main class="auth"><section><a class="brand" href="#home"><b>S</b> skillcircle</a><p class="eyebrow">STUDENT NETWORK</p><h1>Find your people.</h1><p class="muted">Build your circle around skills, ideas, and projects.</p><form id="login-form"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="primary">Sign in</button></form><button class="secondary" id="google">Continue with Google</button><button class="link-button" id="signup">Create an account</button><p class="error">${escapeHtml(message)}</p></section></main>`; document.querySelector("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.target); try { await signInWithEmailAndPassword(auth, data.get("email"), data.get("password")); } catch (error) { loginView(error.message); } }); document.querySelector("#google").addEventListener("click", async () => { try { await signInWithPopup(auth, new GoogleAuthProvider()); } catch (error) { loginView(error.message); } }); document.querySelector("#signup").addEventListener("click", () => { const form = document.querySelector("#login-form"); form.querySelector("button").textContent = "Create account"; form.onsubmit = async (event) => { event.preventDefault(); const data = new FormData(form); try { await createUserWithEmailAndPassword(auth, data.get("email"), data.get("password")); } catch (error) { loginView(error.message); } }; }); }

async function homeView() { const data = await request("/feed"); profile = data.profile; feed = data.posts; app.innerHTML = shell(`<main class="page"><aside class="rail">${avatar(profile)}<h2>${escapeHtml(profile.name)}</h2><p>${escapeHtml(profile.headline)}</p><a href="#profile">View profile →</a></aside><section class="feed"><p class="eyebrow">YOUR CIRCLE</p><h1>Good morning, ${escapeHtml(profile.name.split(" ")[0])}.</h1><form id="post-form" class="composer"><textarea name="content" maxlength="1000" required placeholder="Share something you are learning or building..."></textarea><input name="image" type="file" accept="image/jpeg,image/png,image/webp"><button class="primary">Post</button></form><div id="posts">${feed.map(postCard).join("")}</div></section></main>`); bindShell(); document.querySelector("#post-form").addEventListener("submit", createPost); document.querySelectorAll("[data-like]").forEach((button) => button.addEventListener("click", () => likePost(button.dataset.like))); document.querySelectorAll("[data-comment]").forEach((form) => form.addEventListener("submit", addComment)); }
function postCard(post) { return `<article class="post"><header>${avatar(post.author)}<div><b>${escapeHtml(post.author.name)}</b><p>${escapeHtml(post.author.headline)}</p><small>${timeAgo(post.createdAt)}</small></div></header><p>${escapeHtml(post.content)}</p>${post.imageUrl ? `<img class="post-image" src="${escapeHtml(post.imageUrl)}" alt="Post attachment">` : ""}<footer><button data-like="${post.id}">♡ ${post.likedBy.length || "Like"}</button><button>◌ ${post.comments.length || "Comment"}</button></footer><div class="comments">${post.comments.map((comment) => `<p><b>${escapeHtml(comment.author.name)}</b> ${escapeHtml(comment.text)}</p>`).join("")}<form data-comment="${post.id}"><input name="text" placeholder="Add a thoughtful comment..." required><button>→</button></form></div></article>`; }
async function createPost(event) { event.preventDefault(); try { const body = new FormData(event.target); await request("/posts", { method: "POST", body }); await homeView(); } catch (error) { alert(error.message); } }
async function likePost(id) { try { await request(`/posts/${id}/like`, { method: "POST" }); await homeView(); } catch (error) { alert(error.message); } }
async function addComment(event) { event.preventDefault(); try { const body = new FormData(event.target); await request(`/posts/${event.target.dataset.comment}/comments`, { method: "POST", body: JSON.stringify({ text: body.get("text") }) }); await homeView(); } catch (error) { alert(error.message); } }

async function discoverView() { const people = await request(`/discover${location.search || ""}`); app.innerHTML = shell(`<main class="page narrow"><p class="eyebrow">DISCOVER STUDENTS</p><h1>Find your people.</h1><form id="search" class="search"><input name="q" placeholder="Search name, college, skills, or interests"><button class="primary">Search</button></form><div class="grid">${people.map((person) => `<article class="person">${avatar(person)}<h2>${escapeHtml(person.name)}</h2><p>${escapeHtml(person.headline)}</p><small>${escapeHtml(person.college || "Student")}</small><div class="tags">${person.skills.map((skill) => `<span>${escapeHtml(skill)}</span>`).join("")}</div><button class="primary connect" data-connect="${person.uid}">Connect</button></article>`).join("")}</div></main>`); bindShell(); document.querySelector("#search").addEventListener("submit", (event) => { event.preventDefault(); const query = new FormData(event.target).get("q"); location.search = query ? `?q=${encodeURIComponent(query)}` : ""; }); document.querySelectorAll("[data-connect]").forEach((button) => button.addEventListener("click", async () => { try { await request(`/connections/${button.dataset.connect}`, { method: "POST" }); button.textContent = "Requested"; button.disabled = true; } catch (error) { alert(error.message); } })); }
async function notificationsView() { const items = await request("/notifications"); app.innerHTML = shell(`<main class="page narrow"><p class="eyebrow">YOUR ACTIVITY</p><h1>Stay in the loop.</h1><section class="notice-list">${items.length ? items.map((item) => `<article><i></i><div>${escapeHtml(item.message)}<small>${new Date(item.createdAt).toLocaleString()}</small></div></article>`).join("") : "<p class=muted>No new activity yet.</p>"}</section></main>`); bindShell(); }
async function profileView() { profile = await request("/me"); app.innerHTML = shell(`<main class="page narrow"><p class="eyebrow">YOUR PROFILE</p><h1>${escapeHtml(profile.name)}</h1><form id="profile-form" class="profile-form"><label>Name<input name="name" value="${escapeHtml(profile.name)}"></label><label>Headline<input name="headline" value="${escapeHtml(profile.headline)}"></label><label>College<input name="college" value="${escapeHtml(profile.college)}"></label><label>Degree<input name="degree" value="${escapeHtml(profile.degree)}"></label><label>Bio<textarea name="bio">${escapeHtml(profile.bio)}</textarea></label><label>Skills<input name="skills" value="${escapeHtml(profile.skills.join(", "))}"></label><label>Interests<input name="interests" value="${escapeHtml(profile.interests.join(", "))}"></label><label>Projects<input name="projects" value="${escapeHtml(profile.projects.join(", "))}"></label><button class="primary">Save profile</button></form></main>`); bindShell(); document.querySelector("#profile-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.target); const body = Object.fromEntries(data); for (const key of ["skills", "interests", "projects"]) body[key] = body[key].split(",").map((item) => item.trim()).filter(Boolean); try { await request("/profile", { method: "PUT", body: JSON.stringify(body) }); alert("Profile saved"); } catch (error) { alert(error.message); } }); }
async function render() { setTheme(); if (!currentUser) return loginView(); try { if (page === "discover") await discoverView(); else if (page === "notifications") await notificationsView(); else if (page === "profile") await profileView(); else await homeView(); } catch (error) { app.innerHTML = `<main class="loading error">${escapeHtml(error.message)}</main>`; } }

window.addEventListener("hashchange", () => { page = location.hash.slice(1) || "home"; render(); });
setTheme();
fetch("/api/config").then((response) => response.json()).then((publicConfig) => { config = publicConfig; if (firebaseReady()) { auth = getAuth(initializeApp(config)); onAuthStateChanged(auth, (user) => { currentUser = user; render(); }); } else loginView("Add Firebase values to the root .env."); }).catch(() => loginView("The SkillCircle server is not reachable."));
